[package]
name = "nickelodeon"
version = "0.0.1"
edition = "2021"

[dependencies]
config-finder = "0.1.2"
nickel-lang = "1.0.0"
serde = { version = "1.0.166", features = ["derive"] }
serde_json = "1.0.99"
